### ISSUE TITLE
module 'cupy.cuda.memory' has no attribute 'PythonFunctionAllocatorMemory' for FRCNN

### ISSUE THREAD

**Issue by AnubhootiJ** [git-disl/TOG#11]
**The bug**
I tried using the FRCNN model and followed the demo .ipynb file given in the repository. But trying to import the FRCNN model gave me cupy error. It first came to be an Attirbute error for Utils ( module 'cupy' has no attribute 'util') but later started giving this error. I tried to import other models to see if it was happening in other modules too but I was able to import SSD successfully. Can't figure out what's happening here. 

**This is what I tried to import**
from dataset_utils.preprocessing import letterbox_image_padded
from misc_utils.visualization import visualize_detections
from models.frcnn import FRCNN  # <----- This is where I got the error
from PIL import Image
from tog.attacks import *
import os

![image](https://user-images.githubusercontent.com/31142659/128141184-498e1b78-1bd3-4adc-a7cc-602ac4cfdb4d.png)
![image](https://user-images.githubusercontent.com/31142659/128141242-24980348-2fa4-4653-8290-3b362f98a811.png)

**Comment by khchow-gt** [comment]
Which version of cupy are you using?

**Comment by AnubhootiJ** [comment]
I am using cupy-cuda100==7.1.1

I am working on Google Colab and using pip to install the dependency.

**Comment by khchow-gt** [comment]
Would you mind sharing the notebook?

**Comment by khchow-gt** [comment]
Closing this thread due to inactivity.
