### ISSUE TITLE
TypeError: Keras symbolic inputs/outputs do not implement `__len__`

### ISSUE THREAD

**Issue by westeagle96** [git-disl/TOG#12]
Hi, I'm trying to run demo_patch notebook on google colab, but I getting this error 

TypeError: Keras symbolic inputs/outputs do not implement `__len__`. You may be trying to pass Keras symbolic inputs/outputs to a TF API that does not register dispatching, preventing Keras from automatically converting the API call to a lambda layer in the Functional Model. This error will also get raised if you try asserting a symbolic input/output directly.

**Comment by bahulkark** [comment]
hey, did you solve this issue ? I am getting the same error.

**Comment by khchow-gt** [comment]
Which Keras are you using on Colab?

**Comment by khchow-gt** [comment]
Closing this thread due to inactivity.

**Comment by lrq1999** [comment]
This is may caused by incompatible tensorflow and keras version. Check the corresponding version first.
