### ISSUE TITLE
yolov5

### ISSUE THREAD

**Issue by 3322bfr** [git-disl/TOG#13]
Hi, read the paper and listened to the talk, amazing work. I was trying this on different object detection libraries and the one resistant is the yolo from analytics. I wonder if you have already tried it

**Is your feature request related to a problem? Please describe.**
yolov5 is resistant to TOC based on yolov3 current code.

**Describe the solution you'd like**
would be great to be able to compute the gradient with an example file as in yolov3

**Describe alternatives you've considered**
increase epsilon until image is hard to label even for humans

**Additional context**
link to yolov5 https://github.com/ultralytics/yolov5

**Comment by khchow-gt** [comment]
Thank you for your interest in our work. Currently, we do not have plan to expand the supported libraries to Ultralytics but will include it in our TODO list. In the meantime, if you would like to contribute, please feel free to create a pull request.
