### ISSUE TITLE
Video Example

### ISSUE THREAD

**Issue by bdubbs09** [git-disl/TOG#14]
In the repo it is shown an example of the dash cam being attacked. Is there any example of the code that would be used to adapt it to video, or any general guidance? I work heavily with video so seeing an example would be helpful if you happen to have that code around.

Best,
Brandon

**Comment by khchow-gt** [comment]
For video data, you can use `cv2` to extract image frames. You can refer to the link below to get an example:
[https://stackoverflow.com/a/33399711](https://stackoverflow.com/a/33399711)
