### ISSUE TITLE
running the projects on colab 

### ISSUE THREAD

**Issue by zakaria-hajjaji** [git-disl/TOG#16]
hey please can the project run o google colaboratory

**Comment by khchow-gt** [comment]
The Jupyter notebooks should be able to be run on Colab. Make sure the libraries specified in `requirements.txt` have been installed.

**Comment by Midnight93** [comment]
When I have some free time I will release the colab version with step-by-step installation. I tried the notebook on Colab but you need install correctly the libreries like @khchow-gt said.
