### ISSUE TITLE
TOG Mislabelling attack not working with some images

### ISSUE THREAD

**Issue by nikunjpansari** [git-disl/TOG#17]
Hi,
I used test images from the PASCAL VOC 2007 dataset to test all the attacks. However, while running for some images I found the same error as described below. PFA the zip images which give this error. Also, please find attached file (images and main code I used)

I request you to please look into the issue and resolve it at the earliest. (I tried with SSD512,but it is giving error with other models,too)

**System Configuration**
-> Ubuntu OS
-> Virtual env named TOG with the same requirements.txt

![000983](https://user-images.githubusercontent.com/29738672/180570433-60236901-9d48-453e-b9af-a7d5c69eee96.jpg)
![000003](https://user-images.githubusercontent.com/29738672/180570438-26288087-50a9-4a89-9843-4ee4d1c69344.jpg)

[code.zip](https://github.com/git-disl/TOG/files/9172224/code.zip)

**Traceback (most recent call last):
  File "demo_ssd512.py", line 127, in <module>
    x_adv_mislabeling_ml = tog_mislabeling(victim=detector, x_query=x_query, target='ml', n_iter=n_iter, eps=eps, eps_iter=eps_iter)
  File "/home/user/Documents/TOG/tog/attacks.py", line 34, in tog_mislabeling
    mode=target)
  File "/home/user/Documents/TOG/attack_utils/target_utils.py", line 8, in generate_attack_targets
    pred_logits = detections_copy[:, 2:-4]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed_**

**Comment by khchow-gt** [comment]
Could you confirm if the detection results you passed to `generate_attack_targets` contain at least one object?

**Comment by nikunjpansari** [comment]
For both the images and some other images also, it is showing the same error.  The `detection_query` is returning an empty array which is being passed into the `generate_attack_targets` So, I think this may be the reason for the above error, is that so? If it is because of this, can you please resolve it as it won't run for all test images (4972) in PASCAL VOC 2007 dataset then?

**Comment by khchow-gt** [comment]
The above error is generated by empty detection results on benign images. Having at least one detected object is needed for mislabeling attacks as the goal of the attack is to fool the detector to mislabel an **existing** object. Since the images to be skipped depends on the detector you use, it is recommended to simply add an if-clause to skip if the number of detected objects is zero.
