### ISSUE TITLE
No Object Detection Metrics Computation

### ISSUE THREAD

**Issue by nikunjpansari** [git-disl/TOG#18]
Hi,
I have gone through the code. I found eval_tools.py in frcnn_utils which contains the metrics computation code. I was in the assumption that these metrics are computed after executing the attack, but none of the models with an attack or without an attack (Benign or Adversarial) are giving any metrics.

Can you please clarify this?
 Because in the paper you have mentioned the mAP values but in the main code, it doesn't seem to be included.

If you have any updated code, please share that!!

**Comment by khchow-gt** [comment]
#10
