### ISSUE TITLE
vanishing attack and fabrication Attack

### ISSUE THREAD

**Issue by wangxueping78** [git-disl/TOG#19]
Thank you for your great contribution!
I found that the vanishing attack function is the same as the fabric attack function, but why are the detection results after the attack really different?

**Comment by khchow-gt** [comment]
Vanishing and fabrication attacks are different. We reverse the sign of the objective function for the vanishing attack to achieve fabrication. Just like for vanishing attacks, we try to make objectness scores to be minimal but for fabrication attacks, we make objectness cores to be maximal (reversed sign).
