### ISSUE TITLE
patch

### ISSUE THREAD

**Issue by wangxueping78** [git-disl/TOG#20]
I run the 'demo_patch.ipynb' .
I trained my own vehicle datasets and saved the npy files. Everything seems to be going well, but no patch was generated during the test as shown in the figure below.
Can you help me?

![image](https://user-images.githubusercontent.com/43226404/188253604-25815e51-c36a-4692-b007-3097aeb1288d.png)

**Comment by khchow-gt** [comment]
Could you share the xmin, ymin, xmax, ymax values?
