### ISSUE TITLE
ERROR: ResolutionImpossible

### ISSUE THREAD

**Issue by jaeholo** [git-disl/TOG#7]
When I am installing the dependencies, I have the error below:
**ERROR: Cannot install -r ./requirements.txt (line 12), -r ./requirements.txt (line 3), -r ./requirements.txt (line 4), -r ./requirements.txt (line 6), -r ./requirements.txt (line 8), -r ./requirements.txt (line 9) and numpy==1.19.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy==1.19.2
    cupy-cuda100 7.1.1 depends on numpy>=1.9.0
    keras 2.2.4 depends on numpy>=1.9.1
    matplotlib 3.3.2 depends on numpy>=1.15
    scikit-image 0.17.2 depends on numpy>=1.15.1
    tensorboardx 2.0 depends on numpy
    tensorflow-gpu 1.15.4 depends on numpy<1.19.0 and >=1.16.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict**

It seems that the given version of different packages in the requirement.txt conflict, how should I fix this problem?

**Comment by khchow-gt** [comment]
Hi, you could use the following TensorFlow version: 1.14.0

**Comment by jaeholo** [comment]
> Hi, you could use the following TensorFlow version: 1.14.0

Thanks, I would have a try~
