### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by jaeholo** [git-disl/TOG#8]
Hi!

I am trying to run the demo_yolov3_d and I have downloaded the YOLOv3_Darknet53.h5 from dropbox

Now when I am trying to run the code **"detector = YOLOv3_Darknet53(weights=weights)"**,  
there is an error "
AttributeError                            Traceback (most recent call last)
<ipython-input-4-467895c0b4d7> in <module>()
      1 weights = '/home/osr/YOLOv3_Darknet53.h5'  # TODO: Change this path to the victim model's weights
      2 
----> 3 detector = YOLOv3_Darknet53(weights=weights)

/home/osr/TOG/models/yolov3.py in __init__(self, weights, model_img_size, confidence_thresh_default, confidence_thresh_eval)
    241     def __init__(self, weights, model_img_size=(416, 416), confidence_thresh_default=0.20, confidence_thresh_eval=0.01):
    242         super().__init__(weights, yolo_darknet53,
--> 243                          model_img_size, confidence_thresh_default, confidence_thresh_eval)
    244 
    245 

/home/osr/TOG/models/yolov3.py in __init__(self, weights, backbone, model_img_size, confidence_thresh_default, confidence_thresh_eval)
     19 
     20         self.model = backbone(Input(shape=(None, None, 3)), self.num_anchors // 3, self.num_classes)
---> 21         self.model.load_weights(weights)
     22 
     23         self.encoded_detections = [tf.placeholder(dtype=tf.float32,

/home/osr/anaconda3/envs/TOG/lib/python3.6/site-packages/keras/engine/network.py in load_weights(self, filepath, by_name, skip_mismatch, reshape)
   1164             else:
   1165                 saving.load_weights_from_hdf5_group(
-> 1166                     f, self.layers, reshape=reshape)
   1167 
   1168     def _updated_config(self):

/home/osr/anaconda3/envs/TOG/lib/python3.6/site-packages/keras/engine/saving.py in load_weights_from_hdf5_group(f, layers, reshape)
   1002     """
   1003     if 'keras_version' in f.attrs:
-> 1004         original_keras_version = f.attrs['keras_version'].decode('utf8')
   1005     else:
   1006         original_keras_version = '1'

AttributeError: 'str' object has no attribute 'decode' "

I have modifited the path of weights file to my path and I wonder how to fix this TAT

Thanks for helping

**Comment by khchow-gt** [comment]
Hi, you may check out this issue: [](https://github.com/keras-team/keras/issues/14265)
Someone also had the same problem, which can be fixed by lowering the version of h5py

**Comment by jaeholo** [comment]
@khchow-gt Thanks so much~ I have downgraded the version of h5py from 3.1 to 2.10.0 and it works now
