### ISSUE TITLE
load caffe model

### ISSUE THREAD

**Issue by jaeholo** [git-disl/TOG#9]
Hi!

I have a ssd model which is implemented by caffe, is it possible to use this custom model to replace yours in the demo?
If so, how can I do that? Thanks for your help!

**Comment by khchow-gt** [comment]
I think you may try to use a caffe-to-Keras converter to obtain a Keras version of your model first.

**Comment by jaeholo** [comment]
> I think you may try to use a caffe-to-Keras converter to obtain a Keras version of your model first.

@khchow-gt Thanks for your suggestion, so the model like ssd&yolo you use in your project is built in keras? I thought they were built in pytorch and tried to find a caffe to pytorch converter, I was in the wrong way,

**Comment by khchow-gt** [comment]
SSD and YOLOv3 are both Keras. Only Faster R-CNN is PyTorch. That's why in your case, you need a cafffe to Keras converter.

**Comment by jaeholo** [comment]
@khchow-gt I have searched online these days for a caffe2keras converter, yet none of them work for yolo or ssd, all of them only support a few kinds of layers, do you have any recommendation for such a converter? Thanks

**Comment by khchow-gt** [comment]
I am sorry that I haven't tried any converter. I think using the Keras implementation of SSD to retrain the model is a better choice because there can be a lot of problems to fix when you convert a Caffe model to Keras.
